version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: laboratorios
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labs2021
  
  backend:
    build: ./backend
    image: backend_labsadmin
    command: gunicorn labsadmin.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./backend:/labs/
    ports:
       - "8080:8080"
    environment:
      DEV_CHANNEL: false

