version: "3"
services:
  
  backend:
    build: ./backend
    image: backend_labsadmin
    command: gunicorn labsadmin.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./backend:/labs/
    ports:
       - "8080:8080"

